- name: "A-Install"
  color: "72A447"
- name: "A-Seshat"
  color: "8262BE"
- name: "A-Update"
  color: "17BE67"
- name: "Story"
  description: "A change to the product that generates user value on its own. Unit of delivery."
  color: "0BAC47"
- name: "X-Breaking-Change"
  color: "ff7979"
- name: "Z-Arch"
  color: "D601BE"
- name: "Z-ARM"
  color: "5DEC5B"
- name: "Z-Flatpak"
  color: "0CA856"
- name: "Z-Linux"
  color: "7B4A9C"
- name: "Z-macOS"
  color: "500605"
- name: "Z-Official"
  color: "1D2B20"
- name: "Z-Snap"
  color: "29CD95"
- name: "Z-Suse"
  color: "79D07B"
- name: "Z-Wayland"
  color: "94C519"
- name: "Z-Windows"
  color: "0632DE"
