blank_issues_enabled: false
contact_links:
    - name: Bug report for the Element flatpak app
      url: https://github.com/flathub/im.riot.Riot/issues
      about: Please file bugs with the Flatpak application on the respective repository.
