name: Pull Request
on:
    pull_request_target:
        types: [opened, edited, labeled, unlabeled, synchronize]
permissions: {} # We use ELEMENT_BOT_TOKEN instead
jobs:
    action:
        uses: matrix-org/matrix-js-sdk/.github/workflows/pull_request.yaml@develop
        secrets:
            ELEMENT_BOT_TOKEN: ${{ secrets.ELEMENT_BOT_TOKEN }}
