name: Release Drafter
on:
    push:
        branches: [staging]
    workflow_dispatch: {}
concurrency: ${{ github.workflow }}
permissions: {}
jobs:
    draft:
        uses: matrix-org/matrix-js-sdk/.github/workflows/release-drafter-workflow.yml@develop
        permissions:
            contents: write
        with:
            include-changes: element-hq/element-web~$VERSION
